// <auto-generated />
using AspVueBit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspVueBit.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("AspVueBit.Data.CameraParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("CameraAngle")
                        .HasColumnType("double");

                    b.Property<double>("CameraHeight")
                        .HasColumnType("double");

                    b.Property<double>("DistanceToObject")
                        .HasColumnType("double");

                    b.Property<double>("ObjectHeight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("CameraParameters");
                });
#pragma warning restore 612, 618
        }
    }
}
